### ISSUE TITLE
Bolts conflicts

### ISSUE THREAD

**Issue by rlatapy-luna** [parse-community/Parse-SDK-Android#1036]
Hello, I'm using https://github.com/parse-community/Parse-SDK-Android + https://github.com/parse-community/ParseLiveQuery-Android + https://github.com/BoltsFramework/Bolts-Android

I tried to update these 3 dependencies but I got a runtime error (with respective versions 1.24.2, 1.2.0 & 1.4.0). I did not find any workaround, should I move from Bolts-Android to parse's internal bolts?
```
    java.lang.NoSuchMethodError: No static method getCurrentSessionTokenAsync()Lbolts/Task; in class Lcom/parse/ParseUser; or its super classes (declaration of 'com.parse.ParseUser' appears in /data/app/~~vl-z29yK_GYHloVpqsw9dg==/studio.lunabee.lunabeelibrairies-VGje_wxj3G1TZHAYdU6ZTQ==/base.apk)
        at com.parse.livequery.ParseLiveQueryClientImpl$4.onOpen(ParseLiveQueryClientImpl.java:385)
        at com.parse.livequery.OkHttp3SocketClientFactory$OkHttp3WebSocketClient$1.onOpen(OkHttp3SocketClientFactory.java:48)
        at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:208)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by mtrezza** [comment]
Hi @rlatapy-luna, thanks for reporting.

- Are you getting this error only since updating the Parse SDK to 1.24.2? If yes, does the error not occur when downgrading to 1.24.1?
- Can you share the code you are using to get this error?

**Comment by mtrezza** [comment]
Result of https://github.com/parse-community/Parse-SDK-Android/pull/1033

**Comment by rlatapy-luna** [comment]
> Hi @rlatapy-luna, thanks for reporting. I assume you are only getting this error with Parse SDK 1.24.2 and not if you downgrade to 1.24.1, correct?

I had to go back to parse SDK 1.23.1 and liveQuery 1.1.0 to get it works. With 1.24.1, I'm not able to build because of collisions with Bolts.
I can tried to reproduce in a smaller project if you need. Thanks !

**Comment by mtrezza** [comment]
@rlatapy-luna Can you try to use https://github.com/parse-community/ParseLiveQuery-Android/pull/111/commits/14a90b4b8029e6cafefb98942092ab2111d3cffe and see if it works?

**Comment by rlatapy-luna** [comment]
@mtrezza I cannot fetch com.github.parse-community:ParseLiveQuery-Android:14a90b4 🤔 (Failed to resolve). I don't why sorry, is it working on your side?
